server:
  port: 20000
  servlet:
    session:
      timeout: 30m


spring:
  application:
    name: gulimall-auth-server

  redis:
    host: 39.107.96.120
    port: 6379
  session:
    store-type: redis