server:
  port: 13000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.96.120:8848

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.boyiz.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

